# Generated by Django 5.0.6 on 2024-06-27 04:39

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Insight Comments',
                'db_table': 'InsightComments',
            },
        ),
        migrations.CreateModel(
            name='Insights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', tinymce.models.HTMLField()),
                ('cover_image', models.ImageField(help_text="Upload a profile picture. The image will be stored in the 'blog_cover/' directory.", upload_to='blog_cover/')),
                ('keywords', models.TextField(help_text='Do not add more then five keyword this is only for SEO')),
                ('category', models.CharField(choices=[('SCIENCE_AND_TECHNOLOGY', 'Science and technology'), ('EDUCATION', 'Education'), ('IMMIGRATION', 'Immigration')], max_length=100)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ISN Insights',
                'db_table': 'Insights',
            },
        ),
        migrations.DeleteModel(
            name='NumberOfStudentStudyInUS',
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'DRAFT'), ('PUBLISHED', 'PUBLISHED'), ('PENDING', 'PENDING'), ('REVIEWING', 'REVIEWING'), ('UNPUBLISHED', 'UNPUBLISHED')], max_length=200),
        ),
        migrations.AddField(
            model_name='insightcomments',
            name='insight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.insights'),
        ),
    ]
