# Generated by Django 5.0.7 on 2024-09-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyforcareer',
            name='currency_type',
            field=models.CharField(default='USD', max_length=200),
        ),
    ]
