# Generated by Django 4.0 on 2024-07-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insights',
            name='cover_image',
            field=models.ImageField(help_text='Upload a cover picture. which height recommended size is 2,00x1,334 ', upload_to='blog_cover/'),
        ),
        migrations.AlterField(
            model_name='isnteam',
            name='profile_image',
            field=models.ImageField(help_text='recommended size is 612x408', upload_to='team_profile'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='photo',
            field=models.ImageField(blank=True, help_text='Recommended size is 500x500', null=True, upload_to='testimonial/photo'),
        ),
    ]
