# Generated by Django 5.0.6 on 2024-06-27 17:28

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_insightcomments_insights_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrierOpportunities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('job_title', models.TextField()),
                ('job_description', tinymce.models.HTMLField()),
                ('category', models.CharField(choices=[('ENGINEERING', 'Engineering'), ('DESIGN', 'Design')], max_length=100)),
                ('keyword', models.TextField(help_text='only for SEO write a keyword seperated by comma(,) eg: python,django,hr')),
                ('job_mode', models.CharField(choices=[('REMOTE', 'Remote'), ('ON_SITE', 'On Site'), ('HYBRID', 'Hybrid')], max_length=50)),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time')], max_length=50)),
                ('job_status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLISHED', 'PUBLISHED'), ('PENDING', 'PENDING'), ('REVIEWING', 'REVIEWING'), ('UNPUBLISHED', 'UNPUBLISHED')], max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Currier Opportunities',
                'db_table': 'CurrierOpportunities',
            },
        ),
        migrations.AddField(
            model_name='partnershiprequest',
            name='is_accept_privacy_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='name',
            field=models.CharField(default='Privacy and Policy', max_length=200),
        ),
    ]
