# Generated by Django 5.0.7 on 2024-09-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_applyforcareer_currency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyforcareer',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('PREFER_NOT_TO_SAY', 'Prefer Not To Say')], max_length=100, null=True),
        ),
    ]
