# Generated by Django 4.0 on 2024-07-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_alter_insights_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='message',
            field=models.TextField(),
        ),
    ]
