# Generated by Django 5.0.7 on 2024-09-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_alter_applyforcareer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyforcareer',
            name='pay_period',
            field=models.CharField(blank=True, choices=[('Project', 'Project'), ('Hourly', 'Hourly'), ('Biweekly', 'Biweekly'), ('Monthly', 'Monthly')], max_length=100, null=True),
        ),
    ]
