# Generated by Django 5.0.6 on 2024-06-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_currieropportunities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISNTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=300)),
                ('profile_image', models.ImageField(upload_to='team_profile')),
            ],
            options={
                'verbose_name_plural': 'Our Teams',
                'db_table': 'teams',
            },
        ),
    ]
