# Generated by Django 5.0.6 on 2024-06-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_isnteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnershiprequest',
            name='interested_service',
            field=models.CharField(max_length=100),
        ),
    ]
