# Generated by Django 4.0 on 2024-09-11 15:14

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_applyforcareer_pay_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('source', tinymce.models.HTMLField()),
                ('status', models.CharField(blank=True, choices=[('DRAFT', 'DRAFT'), ('PUBLISHED', 'PUBLISHED'), ('PENDING', 'PENDING'), ('REVIEWING', 'REVIEWING'), ('UNPUBLISHED', 'UNPUBLISHED')], max_length=200)),
            ],
            options={
                'verbose_name_plural': 'DataSource',
                'db_table': 'DataSource',
            },
        ),
        migrations.AlterField(
            model_name='applyforcareer',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partnershiprequest',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
