# Generated by Django 5.0.6 on 2024-07-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_alter_partnershiprequest_interested_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(choices=[('FACEBOOK', 'FACEBOOK'), ('YOUTUBE', 'YOUTUBE'), ('LINKEDIN', 'LINKEDIN'), ('TICKTOK', 'TICKTOK'), ('TWITTER', 'TWITTER')], max_length=100)),
                ('followers', models.CharField(blank=True, default='', max_length=100)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Social Media',
                'db_table': 'social_media',
            },
        ),
    ]
