# Generated by Django 5.0.6 on 2024-07-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(choices=[('FACEBOOK', 'FACEBOOK'), ('YOUTUBE', 'YOUTUBE'), ('LINKEDIN', 'LINKEDIN'), ('TICKTOK', 'TICKTOK'), ('TWITTER', 'TWITTER')], max_length=100, unique=True),
        ),
    ]
