# Generated by Django 5.0.6 on 2024-07-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_alter_socialmedia_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(choices=[('FACEBOOK', 'FACEBOOK'), ('YOUTUBE', 'YOUTUBE'), ('LINKEDIN', 'LINKEDIN'), ('TICKTOK', 'TICKTOK'), ('TWITTER', 'TWITTER'), ('INSTAGRAM', 'INSTAGRAM')], max_length=100, unique=True),
        ),
    ]
