# Generated by Django 5.0.6 on 2024-07-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_alter_socialmedia_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
                'db_table': 'testimonial',
            },
        ),
    ]
