# Generated by Django 5.0.6 on 2024-07-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonial/photo'),
        ),
    ]
