# Generated by Django 5.0.6 on 2024-07-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_testimonials_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='currieropportunities',
            name='job_summary',
            field=models.TextField(default='', help_text='Job summary should less then 500 character', max_length=500),
        ),
    ]
