# Generated by Django 5.0.6 on 2024-07-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0011_currieropportunities_job_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
