# Generated by Django 5.0.6 on 2024-07-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0014_alter_applyforcurrier_contact_phone_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyforcurrier',
            name='availability_or_notice_period',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='applyforcurrier',
            name='other_job_consider',
            field=models.BooleanField(default=False, help_text='I authorize ISN to consider me for other job opportunities for the next 36 months within ISN in addition to the specific job I am applying for.'),
        ),
    ]
